sudo: false
cache:
directories:
- $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37
    - python: "pypy"
      env: TOXENV=pypy
    - python: "3.6"
      env: TOXENV=packaging


install:
  - "pip install -r requirements.txt"

script:
  - tox


before_install:
  - pip install codecov coverage


after_success:
  - tox -e coverage-report
  - COVERAGE_FILE=.tox/.coverage coverage xml
  - codecov -f coverage.xml
